services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    dcqtv.topic:
        class: AppBundle\DcqtvTopic
        tags:
            - { name: gos_web_socket.topic }