

dcqtv_topic:
    channel: dcqtv/lobby/{lobby_id}
    handler:
        callback: 'dcqtv.topic' #related to the getName() of your topic
    requirements:
        lobby_id:
            pattern: "\d+|\D+"

dcqtv_saloon:
    channel: dcqtv/saloon
    handler:
        callback: 'dcqtv.topic' #related to the getName() of your topic